### ISSUE TITLE
Question about guzzle

### ISSUE THREAD

**Issue by djnordeen** [2amigos/google-places-library#1]
Hello, does this library need guzzle 6?

I get this error when trying to update the Google Map Library extension:
` Problem 1
    - Installation request for 2amigos/yii2-google-places-library * -> satisfiable by 2amigos/yii2-google-places-library[0.1.0].
    - 2amigos/yii2-google-places-library 0.1.0 requires guzzlehttp/guzzle 4.* -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.0-rc.1, 4.0.0-rc.2, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev] but these conflict with your requirements or minimum-stability.`

**Comment by tonydspaniard** [comment]
That issue is not part of this library. But I am going to fix it. Thanks for reporting. 

On your case, it seems the issue is with composer. Add this to your composer file: 

```php 
"minimum-stability": "dev",
"prefer-stable": true,
